### PR TITLE
Helpdesk (issue tickets)

### PR DESCRIPTION
**Pull request by aiwenar**

### CODE REVIEW

**Comment by PiotrKozlowski** [comment]
Few questions:
- How to close ticket?
- How to add user to the support team?

**Comment by aiwenar** [comment]
I've left closing tickets out for now, as we haven't yet discussed how we want to do it.

**Comment by PiotrKozlowski** [comment]
`GET /api/v1/support/tickets` is not returning `ticket.is_open`

It would be nice to have `ticket.open_date` and `ticket.close_date`

> I've left closing tickets out for now, as we haven't yet discussed how we want to do it.

I think users should not be able to send new messages to closed tickets, but they should be able to open this ticket again.

**Comment by PiotrKozlowski** [comment]
`Ticket` should also have field `creator` and `members` so members of support team can easily know if someone else already joined conversation with user and they would be able to search ticket by user / date (comment before).

**Pull request merged**
